### ISSUE TITLE
Problem applying fix, met with this error.

### ISSUE THREAD

**Issue by danielos123ssa** [helgoboss/native-instruments-fix#1]
![Annotation 2020-07-01 200022](https://user-images.githubusercontent.com/67702499/86265929-83176c80-bbd5-11ea-9ed9-68cee49bbceb.png)

**Comment by danielos123ssa** [comment]
in need of this script, hope you bother to fix it. @helgoboss

**Comment by helgoboss** [comment]
Wow, didn't think this script would be necessary anymore in 2020. I didn't have this issue so far with current versions of Komplete. But then, loading NI stuff still is comparatively slow ... so maybe the problem just got less severe for some.

The error you are seeing is not related to the script itself but to the utility program "sfk.exe" (Swiss File Knife) which is included in this repository. You could try to replace it with an up-to-date version, maybe the 64-bit one: http://stahlworks.com/dev/swiss-file-knife.html. Googling the error message also spits out some approaches how to fix this kind of error.

Alternative: Carry out the steps done in the script manually (described in the README).

Good luck!

**Comment by danielos123ssa** [comment]
haha wow, using x64 bit version of sfk.exe I was able to apply your fix and it did in fact work! :D thank you for making this obscure but such useful fix.
